package css.com.applab.countrylist.layout;

import android.content.Context;
import android.graphics.Typeface;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ImageView.ScaleType;
import android.widget.LinearLayout;
import android.widget.LinearLayout.LayoutParams;
import android.widget.RelativeLayout;
import android.widget.TextView;

import com.mob.tools.utils.R;

public class IdentifyNumPageLayout extends BasePageLayout {
    public IdentifyNumPageLayout(Context c) {
        super(c, false);
    }

    protected void onCreateContent(LinearLayout parent) {
        LinearLayout wrapperLayout = new LinearLayout(this.context);
        LayoutParams wrapperParams = new LayoutParams(-1, -1);
        wrapperLayout.setLayoutParams(wrapperParams);
        wrapperLayout.setBackgroundColor(-1);
        wrapperLayout.setOrientation(1);
        wrapperLayout.setPadding(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26), 0, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26), 0);
        parent.addView(wrapperLayout);
        TextView identifyNotify = new TextView(this.context);
        identifyNotify.setId(1881145356);
        LayoutParams identifyNotifyParams = new LayoutParams(-1, -2);
        identifyNotifyParams.topMargin = cn.smssdk.gui.layout.SizeHelper.fromPxWidth(32);
        identifyNotify.setGravity(17);
        identifyNotify.setLayoutParams(identifyNotifyParams);
        int resid = R.getStringRes(this.context, "smssdk_make_sure_mobile_detail");
        identifyNotify.setText(resid);
        identifyNotify.setTextColor(-6710887);
        identifyNotify.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(24));
        wrapperLayout.addView(identifyNotify);
        TextView phone = new TextView(this.context);
        phone.setId(1881145357);
        LayoutParams phoneParams = new LayoutParams(-1, -2);
        phoneParams.topMargin = cn.smssdk.gui.layout.SizeHelper.fromPxWidth(50);
        phone.setGravity(17);
        phone.setLayoutParams(identifyNotifyParams);
        phone.setTextColor(-13290187);
        phone.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26));
        phone.setTypeface(Typeface.DEFAULT_BOLD);
        wrapperLayout.addView(phone);
        RelativeLayout inputBg = new RelativeLayout(this.context);
        LayoutParams inputBgParams = new LayoutParams(-1, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(72));
        inputBgParams.topMargin = cn.smssdk.gui.layout.SizeHelper.fromPxWidth(38);
        inputBg.setLayoutParams(inputBgParams);
        resid = R.getBitmapRes(this.context, "smssdk_input_bg_focus");
        inputBg.setBackgroundResource(resid);
        wrapperLayout.addView(inputBg);
        android.widget.RelativeLayout.LayoutParams putIdentifyParams = new android.widget.RelativeLayout.LayoutParams(-1, -1);
        putIdentifyParams.leftMargin = cn.smssdk.gui.layout.SizeHelper.fromPxWidth(18);
        EditText putIdentify = new EditText(this.context);
        putIdentify.setLayoutParams(putIdentifyParams);
        putIdentify.setId(117506054);
        resid = R.getStringRes(this.context, "smssdk_write_identify_code");
        putIdentify.setHint(resid);
        putIdentify.setBackgroundColor(-1);
        putIdentify.setSingleLine(true);
        putIdentify.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(24));
        putIdentify.setInputType(2);
        inputBg.addView(putIdentify);
        android.widget.RelativeLayout.LayoutParams clearImageParams = new android.widget.RelativeLayout.LayoutParams(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(34), cn.smssdk.gui.layout.SizeHelper.fromPxWidth(34));
        clearImageParams.addRule(15);
        clearImageParams.addRule(7, 117506054);
        ImageView clearImage = new ImageView(this.context);
        clearImage.setLayoutParams(clearImageParams);
        clearImage.setId(117571589);
        resid = R.getBitmapRes(this.context, "smssdk_clear_search");
        clearImage.setImageResource(resid);
        clearImage.setScaleType(ScaleType.FIT_CENTER);
        clearImage.setVisibility(8);
        inputBg.addView(clearImage);
        Button soundBtn = new Button(this.context);
        soundBtn.setId(1881145358);
        android.widget.RelativeLayout.LayoutParams soundParams = new android.widget.RelativeLayout.LayoutParams(-2, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(54));
        soundParams.addRule(12);
        soundParams.addRule(7, 117506054);
        soundBtn.setLayoutParams(soundParams);
        resid = R.getBitmapRes(this.context, "smssdk_btn_disenable");
        soundBtn.setBackgroundResource(resid);
        resid = R.getStringRes(this.context, "smssdk_send_sounds");
        soundBtn.setText(resid);
        soundBtn.setTextColor(-1);
        soundBtn.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(20));
        int padding = cn.smssdk.gui.layout.SizeHelper.fromPxWidth(18);
        soundBtn.setPadding(padding, 0, padding, 0);
        soundBtn.setVisibility(8);
        inputBg.addView(soundBtn);
        TextView unreceive = new TextView(this.context);
        unreceive.setId(1881145359);
        LayoutParams unreceiveParams = new LayoutParams(-1, -2);
        unreceiveParams.setMargins(0, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(34), 0, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(30));
        unreceive.setLayoutParams(unreceiveParams);
        unreceive.setGravity(17);
        resid = R.getStringRes(this.context, "smssdk_receive_msg");
        unreceive.setText(resid);
        unreceive.setTextColor(-10724260);
        unreceive.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(22));
        wrapperLayout.addView(unreceive);
        Button submitBtn = new Button(this.context);
        submitBtn.setId(1881145360);
        LayoutParams submitParams = new LayoutParams(-1, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(72));
        submitBtn.setLayoutParams(submitParams);
        resid = R.getBitmapRes(this.context, "smssdk_btn_disenable");
        submitBtn.setBackgroundResource(resid);
        resid = R.getStringRes(this.context, "smssdk_next");
        submitBtn.setText(resid);
        submitBtn.setTextColor(-1);
        submitBtn.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(24));
        submitBtn.setPadding(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(10), 0, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(10), 0);
        wrapperLayout.addView(submitBtn);
    }
}
