package css.com.applab.countrylist.layout;

import android.content.Context;
import android.graphics.drawable.Drawable;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.ImageView.ScaleType;
import android.widget.LinearLayout;
import android.widget.LinearLayout.LayoutParams;
import android.widget.TextView;

import com.mob.tools.utils.R;

public class RegisterPageLayout extends BasePageLayout {
    public RegisterPageLayout(Context context) {
        super(context, false);
    }

    protected void onCreateContent(LinearLayout parent) {
        cn.smssdk.gui.layout.SizeHelper.prepare(this.context);
        LinearLayout rlCountry = new LinearLayout(this.context);
        LayoutParams params = new LayoutParams(-1, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(96));
        params.setMargins(cn.smssdk.gui.layout.SizeHelper.fromPx(26), cn.smssdk.gui.layout.SizeHelper.fromPxWidth(32), cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26), 0);
        rlCountry.setLayoutParams(params);
        rlCountry.setId(117571585);
        TextView tv = new TextView(this.context);
        LayoutParams tvParams = new LayoutParams(-2, -2);
        tvParams.gravity = 16;
        tv.setLayoutParams(tvParams);
        tv.setPadding(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(14), 0, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(14), 0);
        int resid = R.getStringRes(this.context, "smssdk_country");
        tv.setText(resid);
        tv.setTextColor(-16777216);
        tv.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(25));
        rlCountry.addView(tv);
        TextView tvCountry = new TextView(this.context);
        tvCountry.setId(117571586);
        LayoutParams tvCountryParams = new LayoutParams(-2, -2);
        tvCountryParams.gravity = 16;
        tvCountryParams.weight = 1.0F;
        tvCountryParams.rightMargin = cn.smssdk.gui.layout.SizeHelper.fromPxWidth(14);
        tvCountry.setLayoutParams(tvCountryParams);
        tvCountry.setGravity(5);
        tvCountry.setPadding(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(14), 0, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(14), 0);
        tvCountry.setTextColor(-12206054);
        tvCountry.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(25));
        rlCountry.addView(tvCountry);
        parent.addView(rlCountry);
        View line = new View(this.context);
        LayoutParams lineParams = new LayoutParams(-2, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(1));
        lineParams.leftMargin = cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26);
        lineParams.rightMargin = cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26);
        line.setLayoutParams(lineParams);
        line.setBackgroundColor(-855310);
        parent.addView(line);
        LinearLayout phoneLayout = new LinearLayout(this.context);
        LayoutParams phoneParams = new LayoutParams(-1, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(70));
        phoneParams.setMargins(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26), cn.smssdk.gui.layout.SizeHelper.fromPxWidth(30), cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26), 0);
        phoneLayout.setLayoutParams(phoneParams);
        TextView countryNum = new TextView(this.context);
        countryNum.setId(117571587);
        LayoutParams countryNumParams = new LayoutParams(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(104), -1);
        countryNum.setLayoutParams(countryNumParams);
        countryNum.setGravity(17);
        countryNum.setTextColor(-13290187);
        countryNum.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(25));
        resid = R.getBitmapRes(this.context, "smssdk_input_bg_focus");
        countryNum.setBackgroundResource(resid);
        phoneLayout.addView(countryNum);
        LinearLayout wrapperLayout = new LinearLayout(this.context);
        LayoutParams wrapperParams = new LayoutParams(0, -1);
        wrapperParams.weight = 1.0F;
        wrapperLayout.setLayoutParams(wrapperParams);
        resid = R.getBitmapRes(this.context, "smssdk_input_bg_special_focus");
        wrapperLayout.setBackgroundResource(resid);
        EditText writePhone = new EditText(this.context);
        writePhone.setId(117571588);
        LayoutParams writePhoneParams = new LayoutParams(0, -2);
        writePhoneParams.gravity = 16;
        writePhoneParams.setMargins(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(10), 0, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(10), 0);
        writePhoneParams.weight = 1.0F;
        writePhone.setLayoutParams(writePhoneParams);
        writePhone.setBackgroundDrawable((Drawable)null);
        resid = R.getStringRes(this.context, "smssdk_write_mobile_phone");
        writePhone.setHint(resid);
        writePhone.setInputType(3);
        writePhone.setTextColor(-13290187);
        writePhone.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(25));
        wrapperLayout.addView(writePhone);
        ImageView image = new ImageView(this.context);
        image.setId(117571589);
        LayoutParams imageParams = new LayoutParams(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(24), cn.smssdk.gui.layout.SizeHelper.fromPxWidth(24));
        imageParams.gravity = 16;
        imageParams.rightMargin = cn.smssdk.gui.layout.SizeHelper.fromPxWidth(20);
        image.setLayoutParams(imageParams);
        resid = R.getBitmapRes(this.context, "smssdk_clear_search");
        image.setBackgroundResource(resid);
        image.setScaleType(ScaleType.CENTER_INSIDE);
        image.setVisibility(8);
        wrapperLayout.addView(image);
        phoneLayout.addView(wrapperLayout);
        parent.addView(phoneLayout);
        Button nextBtn = new Button(this.context);
        nextBtn.setId(117571590);
        LayoutParams nextParams = new LayoutParams(-1, cn.smssdk.gui.layout.SizeHelper.fromPxWidth(72));
        nextParams.setMargins(cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26), cn.smssdk.gui.layout.SizeHelper.fromPxWidth(36), cn.smssdk.gui.layout.SizeHelper.fromPxWidth(26), 0);
        nextBtn.setLayoutParams(nextParams);
        resid = R.getBitmapRes(this.context, "smssdk_btn_disenable");
        nextBtn.setBackgroundResource(resid);
        resid = R.getStringRes(this.context, "smssdk_next");
        nextBtn.setText(resid);
        nextBtn.setTextColor(-1);
        nextBtn.setTextSize(0, (float) cn.smssdk.gui.layout.SizeHelper.fromPxWidth(25));
        nextBtn.setPadding(0, 0, 0, 0);
        parent.addView(nextBtn);
    }
}
